version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "01:00"
    commit-message:
      prefix: "npm"
    groups:
      all:
        patterns:
          - "*"
