export const sign = [
    {
        name: 'aries',
        unicode: '♈︎',
        compatibility: [{
            name: 'taurus',
            value: 50
        }, {
            name: 'gemini',
            value: 82
        }, {
            name: 'cancer',
            value: 21
        }, {
            name: 'leo',
            value: 74
        }, {
            name: 'virgo',
            value: 3
        }, {
            name: 'libra',
            value: 60
        }, {
            name: 'scorpio',
            value: 38
        }]
    }, {
        name: 'taurus',
        unicode: '♉︎',
        compatibility: [{
            name: 'taurus',
            value: 20
        }, {
            name: 'gemini',
            value: 49
        }, {
            name: 'cancer',
            value: 36
        }, {
            name: 'leo',
            value: 89
        }, {
            name: 'virgo',
            value: 64
        }, {
            name: 'libra',
            value: 3
        }, {
            name: 'scorpio',
            value: 68
        }]
    }, {
        name: 'gemini',
        unicode: '♊︎',
        compatibility: [{
            name: 'taurus',
            value: 10
        }, {
            name: 'gemini',
            value: 97
        }, {
            name: 'cancer',
            value: 63
        }, {
            name: 'leo',
            value: 35
        }, {
            name: 'virgo',
            value: 75
        }, {
            name: 'libra',
            value: 26
        }, {
            name: 'scorpio',
            value: 49
        }]
    }, {
        name: 'cancer',
        unicode: '♋︎',
        compatibility: [{
            name: 'taurus',
            value: 45
        }, {
            name: 'gemini',
            value: 15
        }, {
            name: 'cancer',
            value: 35
        }, {
            name: 'leo',
            value: 90
        }, {
            name: 'virgo',
            value: 81
        }, {
            name: 'libra',
            value: 23
        }, {
            name: 'scorpio',
            value: 12
        }]
    }, {
        name: 'leo',
        unicode: '♌︎',
        compatibility: [{
            name: 'taurus',
            value: 78
        }, {
            name: 'gemini',
            value: 54
        }, {
            name: 'cancer',
            value: 36
        }, {
            name: 'leo',
            value: 64
        }, {
            name: 'virgo',
            value: 21
        }, {
            name: 'libra',
            value: 41
        }, {
            name: 'scorpio',
            value: 37
        }]
    }, {
        name: 'virgo',
        unicode: '♍︎',
        compatibility: [{
            name: 'taurus',
            value: 95
        }, {
            name: 'gemini',
            value: 65
        }, {
            name: 'cancer',
            value: 43
        }, {
            name: 'leo',
            value: 66
        }, {
            name: 'virgo',
            value: 88
        }, {
            name: 'libra',
            value: 11
        }, {
            name: 'scorpio',
            value: 22
        }]
    }, {
        name: 'libra',
        unicode: '♎︎',
        compatibility: [{
            name: 'taurus',
            value: 35
        }, {
            name: 'gemini',
            value: 48
        }, {
            name: 'cancer',
            value: 92
        }, {
            name: 'leo',
            value: 61
        }, {
            name: 'virgo',
            value: 11
        }, {
            name: 'libra',
            value: 3
        }, {
            name: 'scorpio',
            value: 75
        }]
    }, {
        name: 'scorpio',
        unicode: '♏︎',
        compatibility: [{
            name: 'taurus',
            value: 72
        }, {
            name: 'gemini',
            value: 50
        }, {
            name: 'cancer',
            value: 30
        }, {
            name: 'leo',
            value: 41
        }, {
            name: 'virgo',
            value: 64
        }, {
            name: 'libra',
            value: 21
        }, {
            name: 'scorpio',
            value: 76
        }]
    }, {
        name: 'sagittarius',
        unicode: '♐︎',
        compatibility: [{
            name: 'taurus',
            value: 81
        }, {
            name: 'gemini',
            value: 34
        }, {
            name: 'cancer',
            value: 71
        }, {
            name: 'leo',
            value: 37
        }, {
            name: 'virgo',
            value: 64
        }, {
            name: 'libra',
            value: 92
        }, {
            name: 'scorpio',
            value: 37
        }]
    }, {
        name: 'capricorn',
        unicode: '♑︎',
        compatibility: [{
            name: 'taurus',
            value: 94
        }, {
            name: 'gemini',
            value: 38
        }, {
            name: 'cancer',
            value: 67
        }, {
            name: 'leo',
            value: 83
        }, {
            name: 'virgo',
            value: 48
        }, {
            name: 'libra',
            value: 72
        }, {
            name: 'scorpio',
            value: 12
        }]
    }, {
        name: 'aquarius',
        unicode: '♒︎',
        compatibility: [{
            name: 'taurus',
            value: 86
        }, {
            name: 'gemini',
            value: 64
        }, {
            name: 'cancer',
            value: 57
        }, {
            name: 'leo',
            value: 12
        }, {
            name: 'virgo',
            value: 35
        }, {
            name: 'libra',
            value: 9
        }, {
            name: 'scorpio',
            value: 41
        }]
    }, {
        name: 'pisces',
        unicode: '♓︎',
        compatibility: [{
            name: 'taurus',
            value: 80
        }, {
            name: 'gemini',
            value: 66
        }, {
            name: 'cancer',
            value: 47
        }, {
            name: 'leo',
            value: 32
        }, {
            name: 'virgo',
            value: 2
        }, {
            name: 'libra',
            value: 74
        }, {
            name: 'scorpio',
            value: 25
        }]
    }
];


